// ACTION TYPES
const ADD_CITY = "ADD_CITY";
const REMOVE_LAST_CITY = "REMOVE_LAST_CITY";
const REMOVE_CITY = "REMOVE_CITY";
const REMOVE_FIRST_CITY  = "REMOVE_FIRST_CITY";
const UPDATE_CITY_DATA = "UPDATE_CITY_DATA";